image: node:latest

stages:
  - deloyTest
  - deploy

cache:
  paths:
  - node_modules/

deployFamilyTest:
  only:
    - test
  stage: deloyTest
  before_script: 
     - apt-get update -y
     - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
     - eval $(ssh-agent -s)
     - which rsync || ( apt-get update -y && apt-get install rsync -y )
     - mkdir -p ~/.ssh
     - echo -e "$K8S_SECRET_SSH_SECRET_KEY" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - echo "$K8S_SECRET_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
     - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "$K8S_SECRET_DEPLOY_USER"
    - echo "$K8S_SECRET_DEPLOY_SERVER"
    - echo "hieu"
    - rsync -a -e "ssh -p 22 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" . ${K8S_SECRET_DEPLOY_USER}@${K8S_SECRET_DEPLOY_SERVER}:/home/${K8S_SECRET_DEPLOY_USER}/services/test-family-be --delete
    - ssh -o "StrictHostKeyChecking=no" ${K8S_SECRET_DEPLOY_USER}@${K8S_SECRET_DEPLOY_SERVER} 'bash scripts/test-family-be.sh'

deployFamily:
  only:
    - master
  stage: deploy
  before_script: 
      - apt-get update -y
      - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
      - eval $(ssh-agent -s)
      - which rsync || ( apt-get update -y && apt-get install rsync -y )
      - mkdir -p ~/.ssh
      - echo -e "$K8S_SECRET_SSH_SECRET_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo "$K8S_SECRET_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
  script:
    - rsync -a -e "ssh -p 22 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" . ${K8S_SECRET_DEPLOY_USER}@${K8S_SECRET_DEPLOY_SERVER}:/home/${K8S_SECRET_DEPLOY_USER}/services/family-be --delete
    - ssh -o "StrictHostKeyChecking=no" ${K8S_SECRET_DEPLOY_USER}@${K8S_SECRET_DEPLOY_SERVER} 'bash scripts/family-be.sh'
